### ISSUE TITLE
转换器和拦截器的关系？

### ISSUE THREAD

**Issue by betgar** [hironi/axios-tutorial#3]
转换器和拦截器的最大的区别之一，transformer里面只能“同步”操作，interceptor里面可以“异步”。

**Comment by ronffy** [comment]
好问题！
你说的基本就是他们的区别了，简单说下我的理解：

请求转换器（transformRequest）主要用来根据data格式，设置http请求头；
响应转换器（transformResponse）可以根据实际业务中服务端返回的数据格式，统一设置转换方法。
拦截器是被包装成了Promise，显然主要是想用它来处理异步的。

汇总下就是：
转换器是处理数据和请求头的，不能处理异步，不会阻断请求和响应流程；
拦截器可以处理异步需求，可以使用拦截器阻断请求或响应流程。

以上。欢迎补充讨论 👏

**Comment by betgar** [comment]
对，现在总结的就比较全面了。
