### ISSUE TITLE
for in 会遍历原型链上的属性

### ISSUE THREAD

**Issue by code-byte-labs** [hironi/axios-tutorial#5]
作者大大在写`axios`的`createInstance`原理：其中有一条注释
```js
// 注：因为extend内部使用的forEach方法对对象做for in 遍历时，只遍历对象本身的属性，
// 而不会遍历原型链上的属性
```
我做过测试并且也查了这个问题，`for in` 并不是只遍历对象本身的属性，也会遍历原型链上的属性，`for in` 不会遍历不可枚举的对象。我不知道是不是我理解的错误，请作者大大能够指点迷惑。

**Comment by ronffy** [comment]
你好，不知道是我没说太明白还是你没理解，我说的是 `extend内部使用的forEach方法对对象做for in 遍历时`，此处的`for in`不是指单纯的原生方法，而是有定语: `extend内部使用的forEach方法内的for in`，此处的`for in`用`Object.prototype.hasOwnProperty`做了一层过滤。

**Comment by code-byte-labs** [comment]
> 你好，不知道是我没说太明白还是你没理解，我说的是 `extend内部使用的forEach方法对对象做for in 遍历时`，此处的`for in`不是指单纯的原生方法，而是有定语: `extend内部使用的forEach方法内的for in`，此处的`for in`用`Object.prototype.hasOwnProperty`做了一层过滤。

懂了，谢谢作者大大！
